### ISSUE TITLE
Bump version on NPM

### ISSUE THREAD

**Issue by tristanoneil** [airbnb/hypernova-react#2]
The version was bumped to `2.0.0` here https://github.com/airbnb/hypernova-react/commit/94819b755ecf93fbddba191d3b4ed167d4f4e130 but it's still `1.0.0` on NPM.

Any chance we can get a release? ✨

**Comment by ljharb** [comment]
That's the version of the dependency, not of hypernova-react - but sure, I'll cut a release of hypernova-react today.

**Comment by tristanoneil** [comment]
@ljharb Oh right. Thanks!

**Comment by ljharb** [comment]
Sorry for the delay; I'm going to let @goatslacker release this when they're back from vacation.

**Comment by goatslacker** [comment]
https://www.npmjs.com/package/hypernova-react
