### ISSUE TITLE
Use hydrate() instead of render()

### ISSUE THREAD

**Issue by wingleung** [airbnb/hypernova-react#27]
As of React 16 a new method is available for hydrating server side rendered HTML on the client side, `.hydrate()`.

How should we address this with hypernova-react? Do we create a separate branch to implement new features from React 16 and up? or do we merge to the current master with backward compatibility?

**Comment by damianleung** [comment]
committed in forked repo damianleung@05e1619ac6fcce0bb3dce5f8cf8b7a902adf53c0

**Comment by goatslacker** [comment]
We can publish a breaking change with the new behavior.

**Comment by ljharb** [comment]
That would close off pre-v16 support; we need to find a way to add this that's semver-minor.

**Comment by goatslacker** [comment]
> That would close off pre-v16 support

We can backport fixes if necessary and this library doesn't change much so it's safe to do unless there's a non-gross way to semver-minor this.

**Comment by ljharb** [comment]
Let's exhaust our options to do it semver-minor tho, before drawing a line in the sand.

**Comment by damianleung** [comment]
@ljharb @goatslacker made it a semver minor change so it's backward compatible. Also reverted the package version, let you guys handle the version bump. https://github.com/damianleung/hypernova-react/pull/1/commits/70f466cda4ed5c5664221fc04840df85d7c13b4e

**Comment by ljharb** [comment]
The peer deps on react and react-dom need to continue allowing 0.14 and v15, as well as adding in 16.

Please feel free to submit the PR and we can review there!

**Comment by ljharb** [comment]
Closed in #30.
