### ISSUE TITLE
share flux instance

### ISSUE THREAD

**Issue by frozenfung** [airbnb/hypernova-react#4]
As title, I got two components which are both isomorphiced. 
Do I have any chance to share the flux (I use [fluxxor](https://github.com/BinaryMuse/fluxxor)) instance between?

I suppose that there are some block in client-side code should be rewritten, but I have no idea how to make it right and not to break the rule.

any advise?

thanks.

**Comment by ljharb** [comment]
If you need two components to share the same instance on the server, you can either a) construct it in both top-level components, or b) wrap both components in one top-level one, such that you only have one rendering on the server.

**Comment by frozenfung** [comment]
thanks man. I'll give it a try.
